### ISSUE TITLE
Placement on edges

### ISSUE THREAD

**Issue by CosteaPaul** [cytoscape/cytoscape.js-popper#30]
Attaching popper to edges works like a charm, but the positioning of them is... strange.
I would like to have them in the middle, but they sometimes pop up much closer to one side than another. Is this something that needs to / can be specified in the creation?

**Comment by maxkfranz** [comment]
The default placement for an edge is the midpoint.  If you've found an issue, please post a reproducible example (e.g. jsbin, codepen).

**Comment by CosteaPaul** [comment]
Looks like it's actually on the "midpoint" only on the X axis:
https://codepen.io/anon/pen/MLBXzz

**Comment by maxkfranz** [comment]
The position is right.  The size dimensions are wrong.

**Comment by CosteaPaul** [comment]
Sorry, i don't follow. The size dimensions of?

**Comment by maxkfranz** [comment]
> Sorry, i don't follow. The size dimensions of?

renderedDimensions : A function that can be used to override the rendered Cytoscape bounding box dimensions considered for the popper target (i.e. cy or ele). It defines only the effective width and height (bb.w and bb.h) of the Popper target. This option is more often useful for elements rather than for the core.

**Comment by maxkfranz** [comment]
Resolved in v1.0.4

**Comment by SnakeAckerman** [comment]
Is there any way to set the popper (or tippy) position on any edge point but the midpoint? In specific, I'd like to set the popper position according to the mouse position on mouseover
