### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by manotoor** [cytoscape/cytoscape.js-popper#35]
Sorry not sure where to ask this.
Is there documentation on how to use popper with react?
Or to use @tippy.js/react with cytoscape?

**Comment by maxkfranz** [comment]
@tippy.js/react is used for tooltips on DOM elements.  You have to use this extension for tooltips on Cytoscape elements.

You have to render a React component within `content` in order to use React within the Tippy’s content with this extension.

Here is an example in an active project: https://github.com/PathwayCommons/factoid/blob/unstable/src/client/components/editor/cy/tippy.js#L395-L399
