### ISSUE TITLE
Interactivity question

### ISSUE THREAD

**Issue by pieartsy** [cytoscape/cytoscape.js-popper#37]
I am not able to figure out how to get an interactive tippy tooltip. Even in the supplied tippy demo, `interactive: true` seems to make the tooltips disappear and the console return `TypeError: t is null`. Commenting that out makes the tooltips appear again.

**Comment by maxkfranz** [comment]
This extension is just a wrapper for Tippy so that Tippy knows how to position a popover on Cytoscape elements.  All the heavy lifting is done by Tippy and Popper.  The authors of Tippy can probably answer your question: https://github.com/atomiks/tippyjs

**Comment by maxkfranz** [comment]
I've confirmed that Tippy works fine with this extension and `interactive: true`.

The demo is meant to be simple, so it doesn't include every combination of options.  You should refer to the Tippy documentation to configure your options for your use case: https://atomiks.github.io/tippyjs/v5/all-props/

In the documentation for the Tippy props, it's mentioned that you must specify `appendTo` if you use `interactive: true` and the `reference` has no parent.  I've updated the demo with an interactive example, because it's a common use case.  However, you should still generally refer to the Tippy documentation for usage details.

**Comment by pieartsy** [comment]
Thank you for looking into this!
