### ISSUE TITLE
Update to Popper.js 2.x (and Tippy example to Tippy.js 6.x)

### ISSUE THREAD

**Issue by ikornienko** [cytoscape/cytoscape.js-popper#39]
Want to get it on radar that Popper.js [latest release](https://github.com/popperjs/popper-core/releases) is `2.1.0`, and Tippy.js [latest release](https://github.com/atomiks/tippyjs/releases) is `6.0.2` (and it has migrated to Popper.js v2).

Note: creation of this issue isn't a claim that I'm going to work on it... as I'm likely not.

**Comment by maxkfranz** [comment]
Our apps are using Tippy v4 and Popper v1, and so far we haven't had a compelling reason to upgrade yet.  This extension should, as of today, work with any version of Tippy that is compatible with Popper v1.

For anyone who's interested in using Popper v2 or Tippy v6, a good first step would be to test the existing demos with upgraded `<script>` references.

**Comment by ikornienko** [comment]
Existing demo will break, as you can see in [Popper.js@2 migration guide](https://popper.js.org/docs/v2/migration-guide/) the API has changed, and `Tippy@6` isn't compatible with `Popper.js@1`. Quick illustration of it is in [this fiddle](https://jsfiddle.net/ikornienko/zjbsry2x/) where `Tippy` fails with `createPopper is not a function` error.

I understand and agree that if someone is using old versions they can keep using them. Though there are a couple of concerns I have with this point of view:
1. Not sure `Popper.js` and `Tippy` maintainers are committed to supporting old versions (bug fixes, security vulns etc.)
2. Let's imagine if someone is already using `Popper.js@2` and `Tippy@6` in their, say, [CRA](https://github.com/facebook/create-react-app) product, and then they have a feature request to show some graph. They choose `cytoscape.js` and `cytoscape.js-popper` to do so. While webpack likely will resolve correctly `Popper.js@1` as a direct dependency for `cytoscape.js-popper`, they will have to jump some hoops to bundle old version of `Tippy` to be used exclusively by that graph code (as they're unlikely will be inclined to downgrade it for the rest of the app). Jumping those hoops is double-hard with [CRA](https://github.com/facebook/create-react-app) where webpack config isn't available for editing.

**Comment by maxkfranz** [comment]
I agree with your assessment, and I think that it would be great to have support for newer versions of Tippy and Popper.  However, we’re not affected by those issue for now, so it’s not a high priority issue for us at the moment.  Anyone who has encountered issues like those — or anyone who is otherwise interested — is welcome to create a pull request.

Thanks for posting the link to the migration guide and the the link to your demo.  They look like a great start.

**Comment by davydhong** [comment]
@ikornienko  my grind working with the latest tippy version was that the documentation for defining the position has been moved to a different selection without a clear declaration.

`getReferenceClientRect`, which is used to control the box location, has been added to the tippy property to match popper. All I needed to do was pass it directly to the instantiation rather than decorating popperInstance.

cytoscape.js-popper documentation probably could use an update in the example section. Here's what I did:

```
function makePopper(ele) {
  let ref = ele.popperRef();

  ele.tippy = tippy(document.createElement('div'), {
    getReferenceClientRect: ref.getBoundingClientRect,
    content: ele.id(),
    onHidden(instance) {
      instance.destroy();
    },
  });
  ele.tippy.show();

  ele.on('mouseout', () => {
    ele.tippy.hide();
  });
}
```

**Comment by maxkfranz** [comment]
I'm pinning this to add visibility to this issue.  @davydhong's snippet shows that Tippy v6 doesn't accept Popper refs, requiring a dummy DOM element.  So anyone who wants to use the latest version of Tippy can safely use the existing extension.

Anyone who's interested in using Popper v2 directly is welcome to make a pull request.
